### PR TITLE
no-legacy-imports rule

### LINKED ISSUE #88: Add rule to disallow legacy lit imports
It would be nice to have a rule to ensure we are not importing legacy import paths.

Rule name could be `no-legacy-imports` which disallows `lit-element` and `lit-html`

### LINKED ISSUE #89: Add rule to disallow usage of `@internalProperty`
With Lit v2, `@internalProperty` has been changed to `@state`. We should add a rule to disallow using `@internalProperty` and suggest switching to `@state.

Rule name could be `no-legacy-decorators`

### PR DESCRIPTION
**Pull request by 43081j**
Fixes #89 
Fixes #88 

this does both in one...

* we look for old decorators and suggest you import their new name from `lit/decorators`
* we look for unchanged decorators and suggest you import them from `lit/decorators`
* we look for any other `lit-element` or `lit-html` imports and suggest you import from `lit`

### CODE REVIEW

**Comment by stramel** [comment]
I can't get this rule to work in the lit-element-starter-ts repo.

Question: Should we add a fix to swap it from `@internalProperty` to `@state`?

**Comment by 43081j** [comment]
@stramel in the end i accidentally wrote the no-legacy-imports rule, so ive gone ahead and renamed this PR and the files.

we don't need a no-legacy-decorators as i think its better to detect it at the source: the import declaration. so have done that as part of this rule rather than us highlighting every individual decorator

**Review by stramel — APPROVED** [review]
LGTM

**Comment by 43081j** [comment]
hey @stramel  i added a little change so we detect reactive-element now too, would you mind having another quick look over it? i also added the end columns to the assertions like you mentioned recently

**Review by stramel — APPROVED** [review]

**Pull request merged**
