### PR TITLE
rule: quoted-expressions

### PR DESCRIPTION
**Pull request by 43081j**
Disallows:

`<foo attr="${val}"></foo>`

Allows:

`<foo attr="foo ${val} bar"></foo>`

@stramel if you get chance can you let me know if this makes sense as a rule, especially the way i've done it. 

i went with the 'dumb' approach - just check if an expression is surrounded by quotes so i dont need to re-traverse the template. this means it will also disallow `<foo @event="${handler}">` but i think thats fine

### CODE REVIEW

**Comment by bennypowers** [comment]
Could this be 
```json
"quoted-expressions": ["error", { "quotes": "always|never" }]
```

**Comment by 43081j** [comment]
i did consider that, but was wondering what the use case ever would be for quoting them

only reason i didn't do it that way..

**Comment by bennypowers** [comment]
since it's a linting rule there's room for project preference

in any event I usually quote always, so it would be better for me to not have to make that lint commit on an existing project

**Comment by 43081j** [comment]
no worries, you are correct 👍  i have already reworked it to have an `always` and `never` option, and am adding a fixer for it so `--fix` will work

**Comment by 43081j** [comment]
ok i've added a fixer and reworked the rule to have an `always`/`never` option (default: `never`).

**Review by stramel — APPROVED** [review]
LGTM

**Pull request merged**
